name: Create ZIP File

on:
  push:
    branches:
      - main

jobs:
  zip-repository:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove .git directory
        run: |
          rm -rf .git
          rm -rf .github

      - name: Upload repository contents
        uses: actions/upload-artifact@v4
        with:
          name: repository-contents
          path: |
            *
            .*
