name: Create ZIP File

on:
  push:
    branches:
      - main

jobs:
  zip-repository:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create temporary directory
        run: |
          mkdir temp_dir
          cp -r * temp_dir/ 2>/dev/null || true  # Copy all files, ignore errors for special files
          cp -r .* temp_dir/ 2>/dev/null || true  # Copy hidden files, ignore errors

      - name: Create zip file
        working-directory: temp_dir
        run: zip -r ../repository-contents.zip .

      - name: Upload zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: repository-contents
          path: repository-contents.zip
