name: Create ZIP File

on:
  push:
    branches:
      - main

jobs:
  zip-repository:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create ZIP File
        run: zip -r repository.zip . -x '*.git*' -x 'repository.zip'

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: repository-zip
          path: repository.zip
